version: '3'
services:
  tfup:
    image: tensorflow/tensorflow:latest-gpu-py3-jupyter 
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - /home/YOUR_USER_ID/home:/opt/home
    environment:
      - PASSWORD:123   # jupyter password
    restart: always
#    runtime: nvidia
#    command: "start-notebook.sh \
#             --NotebookApp.password=${ACCESS_TOKEN} \
#             --NotebookApp.certfile=/etc/ssl/notebook/jupyter.pem"
